const express = require('express')
const cors = require('cors')
const app =express()

const authRoute = require('./src/routes/auth')
const tasksRoute = require('./src/routes/tasks')
const companysRoute = require('./src/routes/companys')
const invitationsRoute = require('./src/routes/invitations')
const contractorsRoute = require('./src/routes/contractors')
const kpirPositionsRoute = require('./src/routes/kpirPositions')
const rePositionsRoute = require('./src/routes/rePositions')

app.use(cors())
app.listen(8080 , () => console.log('Server Up and running'))
app.use(express.json( ))
require("./src/database/connection")

app.use('/api/companys',companysRoute)
app.use('/api/auth' , authRoute )
app.use('/api/tasks',tasksRoute)
app.use('/api/invitations',invitationsRoute)
app.use('/api/contractors',contractorsRoute)
app.use('/api/kpirPositions',kpirPositionsRoute)
app.use('/api/rePositions',rePositionsRoute)
