'use strict'

module.exports = (sequelize,Sequelize) =>{
    return sequelize.define("KpirPosition" ,{
            id:{
                type:Sequelize.UUID(),
                allowNull:false,
                defaultValue:Sequelize.UUIDV4(),
                primaryKey:true
            },
            document:{
                type:Sequelize.STRING(50),
                allowNull:false
            },
            date:{
                type:Sequelize.DATEONLY(),
                allowNull:false
            },
            description:{
                type:Sequelize.STRING(50),
                allowNull:false
            },
            contractorName:{
                type:Sequelize.STRING(50),
                allowNull:true
            },
            contractorPost:{
                type:Sequelize.STRING(6),
                allowNull:true
            },
            contractorPostName:{
                type:Sequelize.STRING(50),
                allowNull:true
            },
            contractorAdres:{
                type:Sequelize.STRING(50),
                allowNull:true
            },
            contractorNip:{
                type:Sequelize.STRING(10),
                allowNull:true
            },
            salesIncome:{
                type:Sequelize.FLOAT(),
                allowNull:true
            },
            otherIncomes:{
                type:Sequelize.FLOAT(),
                allowNull:true
            },
            materialsCosts:{
                type:Sequelize.FLOAT(),
                allowNull:true
            },
            sideCosts:{
                type:Sequelize.FLOAT(),
                allowNull:true
            },
            salaryCosts:{
                type:Sequelize.FLOAT(),
                allowNull:true
            },
            otherCosts:{
                type:Sequelize.FLOAT(),
                allowNull:true
            },
            other:{
                type:Sequelize.FLOAT(),
                allowNull:true
            },
            researchDescription:{
                type:Sequelize.STRING(50),
                allowNull:true
            },
            researchValue:{
                type:Sequelize.FLOAT(),
                allowNull:true
            },
            comments:{
                type:Sequelize.STRING(),
                allowNull:true
            }
        },
        {
            timestamps:false,
            tableName:"KpirPositions"  
        }
    )
}
